The mapping port feature. Synchronization of database configs with corresponding environment. C# idiomatic refactoring.
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #20
Opened 2018-10-13 07:15 UTC by Alksar

- ### Concurrent Test Execution
For сoncurrent test execution of testcontainers tests it is necessary to get random host ports. Now while creating a container you can see a flag `PublishAllPorts = true` which means that the container will be run with a `docker run -P` command publishing all exposed ports on random host ports.
https://github.com/Alksar/testcontainers-dotnet/blob/e44505a0eb07ff9b45dc529089eafe7c733801a8/TestContainers/Core/Containers/GenericContainer.cs#L213
To get a published port you should use a [GetMappedPort(exposedPort) ](https://github.com/Alksar/testcontainers-dotnet/blob/e44505a0eb07ff9b45dc529089eafe7c733801a8/TestContainers/Core/Containers/GenericContainer.cs#L119) on IContainer interface.

- ### Synchronization of database name, user, password with corresponding environment vars
For additional configuration (like in a java repository) you can see a protected [virtual void Configure()](https://github.com/Alksar/testcontainers-dotnet/blob/e44505a0eb07ff9b45dc529089eafe7c733801a8/TestContainers/Core/Containers/GenericContainer.cs#L136) method in GenericContainer class with a stub implementation which is called right before [ApplyConfiguration](https://github.com/Alksar/testcontainers-dotnet/blob/e44505a0eb07ff9b45dc529089eafe7c733801a8/TestContainers/Core/Containers/GenericContainer.cs#L172) while creating a container. 
Children can override it and set an additional configuration. For example containers which are inherited from the DatabaseContainer should be run with the environment vars making database name, user and password corresponding to the values which were set by DatabaseContainerBuilder.  [Example for postgresql](https://github.com/Alksar/testcontainers-dotnet/blob/e44505a0eb07ff9b45dc529089eafe7c733801a8/TestContainers/Core/Containers/PostgreSqlContainer.cs#L22-L29). 

- ### Ideomatic c# refactoring.
Now it will be easier for the .net developers to join the project with the refactoring in accordance with the Microsoft style guides:

1. explicit access modifier
2. advanced collection types like a HashSet or Dictionary
3. const naming
4. improved ContainerBuilder inheritance

2018-10-31 08:13 UTC, Alksar commented
I have updated PR accordingly to last master changes.
For each new container need to perform two steps:
- override "void Configure()" method on container for custom configuration envs, e.t.c
- create container builder if needed for fluent style creation of container

2018-10-31 08:55 UTC, farodin91 commented
@Alksar Cool pull request. This port mapping feature would help us a lot. :heart_eyes:

2018-10-31 12:22 UTC, rnorth commented
Coming from the Java side, I'd strongly suggest that the 'publish all ports' behaviour should be the default. Our users almost never have difficulty understanding the concept, and the benefits are big (parallel test running being one, but also not having to care what else is running on a dev machine or CI box).

2018-10-31 12:51 UTC, Alksar commented
> Coming from the Java side, I'd strongly suggest that the 'publish all ports' behaviour should be the default. Our users almost never have difficulty understanding the concept, and the benefits are big (parallel test running being one, but also not having to care what else is running on a dev machine or CI box).

@rnorth Yep! This PR is exactly about this. `PublishAllPorts = true` will be the default behavior

2018-11-08 21:53 UTC, swissarmykirpan requested changes
@Alksar thank you for putting so much time and effort into contributing. I apologise for taking so long to review your PR. I have made some comments about general themes that are throughout the refactor.

2018-11-08 21:53 UTC, swissarmykirpan commented on TestContainers/Core/Builders/DatabaseContainerBuilder.cs
> +            Container.UserName = userName;
The biggest advantage of writing the FluentBuilder this way is that each “chain” of calls is effectively one giant Constructor Function. These are now intrinsically thread-safe, so if the Builder wants to return the generated Constructor Function for direct invocation, it can be used from as many threads simultaneously as desired, without any sort of concurrent impact.

2018-11-08 21:53 UTC, swissarmykirpan commented on TestContainers.Tests/ContainerTests/RedisWithConfigTests.cs
> +        private readonly IDatabase _cache;
I have left out the `private` accessor on purpose as in c# the default is always `private`

2018-11-08 21:53 UTC, swissarmykirpan commented on TestContainers.Tests/ContainerTests/ContainerTests.cs
> +            .WithLabel("your.custom", "label")
a container can have multiple labels, which is why `WithLabel` accepted `params` of `tuples`

2018-11-08 21:53 UTC, swissarmykirpan commented on TestContainers.Tests/ContainerTests/ContainerTests.cs
> +        public Task InitializeAsync() => _container.StartAsync();
I think I would prefer if we dropped `Async` suffixed methods entirely. The fact that the method returns a `Task` is enough to tell the user that the call can be `awaited`

2018-11-08 21:53 UTC, swissarmykirpan commented on TestContainers/Core/Containers/IContainer.cs
> +    public interface IContainer
I don't see why this is necessary. Especially since we only have one implementation `GenericContainer` and how every other container inherits and extends the `GenericContainer`

2018-11-08 21:53 UTC, swissarmykirpan commented on TestContainers/Core/Containers/DatabaseContainer.cs
> +        protected abstract string GetTestQueryString();
Why do we need this? The fact that not every database has the concept of `TestQuery` such as `Redis`.  Also since the `GetTestQueryString()` method is only being used in the class that it is implemented in, I don't see the value in it

2018-11-17 12:57 UTC, Alksar commented on TestContainers.Tests/ContainerTests/ContainerTests.cs
> +            .WithLabel("your.custom", "label")
The methods for setting multiple values was added.
For manual set key-value values in some cases is convinient to use params tuples, but for usage in code scenarious the better way is IEnumerable<KeyValuePair<T, T>> whitch compatible with Dictionary<T,T>.
The sample in .net core codebase [AddInMemoryCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.memoryconfigurationbuilderextensions.addinmemorycollection?view=aspnetcore-2.1) for IConfiguration

2018-11-17 13:09 UTC, Alksar commented on TestContainers.Tests/ContainerTests/ContainerTests.cs
> +        public Task InitializeAsync() => _container.StartAsync();
done.

but in c# there are examples of async methods that return void and sync methods that return Task)

2018-11-17 13:15 UTC, Alksar commented on TestContainers/Core/Containers/IContainer.cs
> +    public interface IContainer
this interface was added for testability purpose. GenericContainer class depends on the Dotnet.Docker client. It will use for GenericContainer-related tests without Dotnet.Docker integration.

2018-11-17 13:50 UTC, Alksar commented on TestContainers.Tests/ContainerTests/RedisWithConfigTests.cs
> +        private readonly IDatabase _cache;
The main condition of success of the TestContainers-dotnet project is to involve c# developers who are interested in microservice testing. For most of them it is extremely comfortable to see the explicit _pritvate_ modifier. For example see the links for most important and popular projects below.

[AspNetCore](https://github.com/aspnet/AspNetCore/blob/dcba1953de0ed91cc369cbb41be5305d8944e33f/src/Servers/Kestrel/Core/src/KestrelServer.cs#L23)
[EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/blob/a3df463cd11669a8ce7617a1d635c61a7fc8ff8a/src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorCache.cs#L19)
[Blazor](https://github.com/aspnet/Blazor/blob/892efc501e3b5f2f911eca93a1cfd7268dc03510/src/Microsoft.AspNetCore.Blazor.Server/Circuits/RenderBatchWriter.cs#L36)
[Ocelot](https://github.com/ThreeMammals/Ocelot/blob/41d4f9c6dfa3069dc9035e2e82d0c46f7f08cf56/src/Ocelot/Request/Creator/DownstreamRequestCreator.cs#L9)
[Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/d535901114c879712fcb60dc6e7bf6963cfc5c82/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs#L15)
and the list goes on and on.

2018-11-21 12:42 UTC, swissarmykirpan requested changes
I'm not sure these changes have really been productive.

 - Creating multiple methods to handle one or N number of objects is not great
 - The outstanding issue of how the fluent builder is not threadsafe anymore has not been addressed

2018-11-21 12:42 UTC, swissarmykirpan commented on TestContainers/Core/Builders/GenericContainerBuilder.cs
> +        public TBuilder WithPortBindings(IEnumerable<KeyValuePair<int, int>> portBindings)
can we go with the tuples notation here please

2018-11-21 12:42 UTC, swissarmykirpan commented on TestContainers/Core/Builders/GenericContainerBuilder.cs
> +        public TBuilder WithLabels(IEnumerable<KeyValuePair<string, string>> labels)
is this neded, the method below does the same job

2018-11-21 12:42 UTC, swissarmykirpan commented on TestContainers/Core/Builders/GenericContainerBuilder.cs
> +        public TBuilder WithMountPoint(Mount mount)
Is this needed?

2018-11-21 12:42 UTC, swissarmykirpan commented on TestContainers/Core/Builders/GenericContainerBuilder.cs
> +        public TBuilder WithMountPoint(Mount mount)
I don't like this pattern of creating one method to handle a single object and another method to handle multiple objects.

2018-11-21 12:42 UTC, swissarmykirpan commented on TestContainers/Core/Builders/GenericContainerBuilder.cs
> +            Container.AddPortBindings(portBindings);
why?

2018-11-24 10:25 UTC, Alksar commented on TestContainers/Core/Containers/DatabaseContainer.cs
> +        protected abstract string GetTestQueryString();
In the current [implementation](https://github.com/testcontainers/testcontainers-dotnet/blob/b4e28405d3b4b1624b2237e4ed90a224ea6693dc/TestContainers/Core/Containers/DatabaseContainer.cs#L21) the TestQueryString property also is present in all databasecontainers becourse it is protected. But if it is not overrided it will be equals `null`. This is error-prone way. 

The right solution here is take out this property to special interface but it wordy. Forcing to explicitly stub implement is also a good because now only redis requires it

2019-09-17 10:48 UTC, closed without merging