Adding RabbitMQ Container
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #21
Opened 2018-10-19 13:10 UTC by farodin91

2018-10-22 22:04 UTC, swissarmykirpan requested changes
Couple of small changes :)

2018-10-22 22:04 UTC, swissarmykirpan commented on TestContainers/Core/Containers/RabbitMQContainer.cs
> +        private IConnectionFactory GetConnectionFactory()
we dont explicity state `private` in this project as it is implicitly set for any property that doesnt have an accessor defined

2018-10-22 22:04 UTC, swissarmykirpan commented on TestContainers/Core/Containers/RabbitMQContainer.cs
> +        private IConnectionFactory GetConnectionFactory()
The factory can be a singleton and so doesnt need to be a method. It could just be a property.

2018-10-23 06:09 UTC, farodin91 commented on TestContainers/Core/Containers/RabbitMQContainer.cs
> +        private IConnectionFactory GetConnectionFactory()
I implemented ConnectionFactory as singleton.

2018-10-25 22:13 UTC, swissarmykirpan approved these changes

2018-10-25 22:14 UTC, merged