Use latest tag for image paths without tag
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #22
Opened 2018-10-31 08:37 UTC by farodin91

2018-11-08 22:01 UTC, swissarmykirpan requested changes
I don't think creating a `Utils` class really benefits us in anyway. I'd rather see the behaviour where it is being used.

Could do something like:

```
var tag = DockerImageName.Split(':').Last();
await _dockerClient.Images.CreateImageAsync(
  new ImagesCreatedParameters
  {
    FromImage = DockerImageName,
    Tag =  tag == DockerImageName ? "latest" : tag
  },.....
```

2018-11-13 07:51 UTC, farodin91 commented
I created this method to make it testable without starting multiple container.

2018-11-27 18:23 UTC, swissarmykirpan commented
It would be better placed in the `Builder` since that is what `Builds` the `Container`.

2018-11-30 12:48 UTC, swissarmykirpan approved these changes

2018-11-30 14:23 UTC, merged