Don't use deprecated GetContainerLogsAsync
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #23
Opened 2018-11-24 09:45 UTC by TheConstructor

Tried to get rid of the deprecation warning. The encoding is the same as in the deprecate function.

2019-02-15 00:31 UTC, swissarmykirpan requested changes
small changes

2019-02-15 00:31 UTC, swissarmykirpan commented on TestContainers/Core/Containers/Container.cs
> +                    using (logs)
why are there two `using` blocks here?

2019-02-16 16:20 UTC, TheConstructor commented
Removed redundant `using`

2019-02-17 12:46 UTC, swissarmykirpan approved these changes

2019-02-17 12:47 UTC, merged