Add support for MsSQL
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #24
Opened 2018-11-24 09:55 UTC by TheConstructor

I ported the MsSqlContainer to .NET, because I (and presumably others) may want to use it.

Tested running on Mac OS X

2019-02-15 00:29 UTC, swissarmykirpan commented on TestContainers/Core/Containers/DatabaseContainer.cs
> +        protected virtual int GetConnectTimeoutSeconds => 120;
might be worth turning this into a `TimeSpan` to give it more flexibility

2019-02-15 00:29 UTC, swissarmykirpan commented on TestContainers/Core/Containers/MsSqlContainer.cs
> +        /// <summary>This will run the container using the Developer Edition (this is the default if no MSSQL_PID environment variable is supplied)</summary>
can we remove the comments here please

2019-02-15 00:30 UTC, swissarmykirpan requested changes
small feedback

2019-02-16 16:10 UTC, TheConstructor commented
@swissarmykirpan I hope I did everything the way you wanted :)

2019-08-10 05:55 UTC, SbiCA commented on TestContainers.Tests/ContainerTests/MsSqlTests.cs
> +            LicenseAcceptance.AcceptLicense("mcr.microsoft.com/mssql/server");
As a user of test container this seems strange to me, Why would I need to call another static calls for accepting the licencse? I would expect that I can use the Fluent API on the `DatabaseContainerBuilder` with something like ``WithAcceptEula()`

2019-08-10 06:04 UTC, SbiCA reviewed
I just had a look at it :)

2019-08-10 06:04 UTC, SbiCA commented on TestContainers/Core/Containers/MsSqlContainer.cs
> +        public const string EDITION_DEVELOPER = "Developer";
Maybe use a typed enum for the editions https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types

2019-08-10 06:04 UTC, SbiCA commented on TestContainers/Core/Containers/MsSqlContainer.cs
> +        protected override TimeSpan GetStartupTimeout => TimeSpan.FromSeconds(240);
Time out seem a bit high to me, but not sure what would be a good fit.

2019-09-17 10:49 UTC, closed without merging