Prepare build pipeline for new version of Testcontainers .NET, closes…
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #46
Opened 2019-06-04 18:37 UTC by HofmeisterAn

I added the first part of the build pipeline, see #41. I will create new issues for the remaining tasks, tomorrow.

@isen-ng I already removed the the StyleCop configurations. I guess it is enough to put your `.editorconfig` into the project.

@swissarmykirpan Could you please update `appveyor.yml`? You just have call the Cake tasks in the single AppVeyor stages, like (for Unix use `build.sh`):

- `build.ps1 --target=Clean`.
- `build.ps1 --target=Restore-NuGet-Packages`.
- `build.ps1 --target=Build`.
- `build.ps1 --target=Test`.

You will find the test results in `test-results` and the coverage file in `test-coverage`.

2019-06-05 10:46 UTC, isen-ng requested changes

2019-06-05 10:46 UTC, isen-ng commented on appveyor.yml
> +  - ps: build.ps1 --target=Restore-NuGet-Packages
This is an ubuntu image, so this should be `build.sh`  instead of `build.ps1` right?

2019-06-05 10:46 UTC, isen-ng commented on src/TestContainers.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Shouldn't the solution file be in the project root?
Then the source projects in a `src` subfolder, and the test projects in the `test` subfolder?
And the `src` and `test` subfolders can be also be virtual folders in the solution too.

Like this project from microsoft:
https://github.com/dotnet/orleans

2019-06-05 10:58 UTC, HofmeisterAn commented on appveyor.yml
> +  - ps: build.ps1 --target=Restore-NuGet-Packages
It shouldn't matter, it looks like PS is installed. `before_test` already used a PS command (`Copy-Item`). But we can change this, ofc.

2019-06-05 11:06 UTC, HofmeisterAn commented on src/TestContainers.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Yes, I tought about that as well. I moved it into `src`, so that the root directory does not contain any source files, just project related information. I will change it to the orleans style.

2019-06-05 11:15 UTC, isen-ng commented on appveyor.yml
> +  - ps: build.ps1 --target=Restore-NuGet-Packages
Since the script is already using powershell, then let's keep it consistent by using powershell everywhere

2019-06-05 11:20 UTC, swissarmykirpan requested changes

2019-06-05 11:20 UTC, swissarmykirpan commented on src/main/TestContainers/Core/Containers/RabbitMQContainer.cs
> -using System;
Not really sure why this is showing up as a diff...

2019-06-05 11:56 UTC, HofmeisterAn commented on src/main/TestContainers/Core/Containers/RabbitMQContainer.cs
> -using System;
Does not occur any more (after merge). I also applied `dotnet format` with @isen-ng `.editorconfig`.

2019-06-06 01:34 UTC, isen-ng approved these changes

2019-06-06 11:03 UTC, swissarmykirpan commented on src/TestContainers/Core/Containers/Container.cs
> +        string _containerId
I really don't like how this looks tbh

2019-06-06 12:13 UTC, isen-ng commented on src/TestContainers/Core/Containers/Container.cs
> +        string _containerId
Actually neither do I.
I set the curly brackets on a new line to true but I think we should disable this for auto properties if it's allowed.

Let me research the .editorconfig.

@HofmeisterAn, I suggest that you revert the dotnet format in this PR so that we can merge your fixes. I will then send another PR for dotnet format and we can discuss it further there.

2019-06-06 14:22 UTC, HofmeisterAn commented on src/TestContainers/Core/Containers/Container.cs
> +        string _containerId
I reverted `dotnet format`. The changes in `RabbitMQContainer` and `RabbitMQTests` are inconsistent eols (crlf to lf). Any other class (expect those two) uses lf. This should be part of `.editorconfig` too. The `dotnet format` PR will set consistent eols in the future.

2019-06-07 01:47 UTC, isen-ng commented
@swissarmykirpan need your approval or dismissal of your review to merge this.

2019-06-07 09:17 UTC, swissarmykirpan commented
apologies, guys - I should have approved and merged this one first, but saw the message too late!

2019-06-07 09:40 UTC, isen-ng commented
Sorry Andre, I managed to rebase your branch against develop successfully!

2019-06-07 09:41 UTC, isen-ng commented
This is now mergable again!

2019-06-07 12:40 UTC, swissarmykirpan commented on test/TestContainers.Tests/ContainerTests/RabbitMQTests.cs
> +    public class RabbitMQTests : IClassFixture<RabbitMQFixture>
what's happened here?

2019-06-07 12:40 UTC, swissarmykirpan requested changes
Still a couple of files are showing changes incorrectly.

2019-06-07 13:09 UTC, HofmeisterAn commented
As I said, those changes are inconsistent line endings and ok. We should merge them, or we will get them within another PR. Every file is lf expect those two.

2019-06-07 13:28 UTC, swissarmykirpan approved these changes

2019-06-07 13:29 UTC, merged