Added various sections into readme
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #58
Opened 2019-06-25 04:01 UTC by lalitkale

Sections Added
- About
- Getting Started
- Features [Features section is focused from end-user standpoint. This can serve as our roadmap. We can tick each box as we proceed further for merging all three implementations] - Need review
- Commands- Need review 
- Examples
- Contributing
- Versioning
- Authors 
- License
- Acknowledgements

closes #57

2019-06-25 05:17 UTC, isen-ng requested changes
One of the purposes of Markdown was to allow writing text that is easily readable without rendering (on a computer screen). Thus the markdown we write should be easily readable without rendering as well. IMO that means no horizontal scrolling, well-inserted new lines, etc.

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +[![Build status](https://ci.appveyor.com/api/projects/status/b20um5dc0ikf8cme/branch/master?svg=true)](https://ci.appveyor.com/project/swissarmykirpan/testcontainers-dotnet-ak6r1/branch/master)[![Cov
You can split the badges into new lines in text without it having new lines in the rendered page. This is more readable when the text is not rendered.

```suggestion
[![Build status](https://ci.appveyor.com/api/projects/status/b20um5dc0ikf8cme/branch/master?svg=true)](https://ci.appveyor.com/project/swissarmykirpan/testcontainers-dotnet-ak6r1/branch/master)
[![Coverage Status](https://coveralls.io/repos/github/testcontainers/testcontainers-dotnet/badge.svg?branch=)](https://coveralls.io/github/testcontainers/testcontainers-dotnet?branch=master) <a href="https://www.nuget.org/packages/TestContainers"><img src="https://img.shields.io/nuget/v/TestContainers.svg?style=flat"></a> 
[![NuGet](https://img.shields.io/nuget/dt/TestContainers.svg)](https://www.nuget.org/packages/TestContainers)
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +Testcontainers is a .NET library  that helps to develop test automation - specially integration test scenarios. Under the hood, it uses  XUnit  framework and docker containers. https://testcontainers
Same over here. Putting in a newline in the text will not put a new line in the rendered markdown. Please keep lines to 120 characters for readability.

```suggestion
Testcontainers is a .NET library  that helps to develop test automation - specially integration test scenarios. Under 
the hood, it uses  XUnit  framework and docker containers. https://testcontainers.org
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +- **Data access layer integration tests**: use a containerised instance of a MySQL, PostgreSQL or Oracle database to test your data access layer code for complete compatibility, but without requiring
Split into new lines of 120 characters or less
```suggestion
- **Data access layer integration tests**: use a containerised instance of a MySQL, PostgreSQL or Oracle database to 
  test your data access layer code for complete compatibility, but without requiring complex setup on developers' 
  machines and safe in the knowledge that your tests will always start with a known DB state. Any other database type 
  that can be containerised can also be used.
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +- **Application integration tests**: for running your application in a short-lived test mode with dependencies, such as databases, message queues or web servers.
```suggestion
- **Application integration tests**: for running your application in a short-lived test mode with dependencies, such 
  as databases, message queues or web servers.
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +- **UI/Acceptance tests**: use containerised web browsers, compatible with Selenium, for conducting automated UI tests. Each test can get a fresh instance of the browser, with no browser state, plugi
```suggestion
- **UI/Acceptance tests**: use containerised web browsers, compatible with Selenium, for conducting automated UI 
  tests. Each test can get a fresh instance of the browser, with no browser state, plugin variations or automated 
  browser upgrades to worry about. And you get a video recording of each test session, or just each session where 
  tests failed.
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +Testcontainers.NET supports Windows, Linux, and macOS as host systems. Linux Docker containers are supported on all three operating systems.
Split into new lines
```suggestion
Testcontainers.NET supports Windows, Linux, and macOS as host systems. Linux Docker containers are supported on all 
three operating systems.
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +Native Windows Docker containers are only supported on Windows. Windows requires the host operating system version to match the container operating system version. You'll find further information abo
```suggestion
Native Windows Docker containers are only supported on Windows. Windows requires the host operating system version to 
match the container operating system version. You'll find further information about Windows container version 
compatibility [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility).
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +Keep in mind to enable the correct Docker engine on Windows host systems to match the container operating system. With Docker CE you can switch the engine with: `$env:ProgramFiles\Docker\Docker\Docke
```suggestion
Keep in mind to enable the correct Docker engine on Windows host systems to match the container operating system. With 
Docker CE you can switch the engine with: `$env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon` or 
`-SwitchLinuxEngine`, `-SwitchWindowsEngine`.
```

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +Here is an example of a pre-configured Testcontainer. In the example, Testcontainers starts a PostgreSQL database and executes a SQL query.
split

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +Please read [CONTRIBUTING.md](CONTRIBUTING.md) for details on our code of conduct, and the process for submitting pull requests to us.
split

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +See also the list of [contributors](https://github.com/testcontainers/testcontainers-dotnet/graphs/contributors) who participated in this project.
split

2019-06-25 05:17 UTC, isen-ng commented on README.md
> +We use [SemVer](http://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/testcontainers/testcontainers-dotnet/tags).
split

2019-06-25 05:19 UTC, isen-ng commented
I'm going to review the formatting first. Once that's settled then I'll move on to the content.

Thank you for the PR @lalitkale

2019-06-25 06:58 UTC, lalitkale commented
@isen-ng thanks for your feedback. This is what makes open source great. I will work on the comments and will update the PR.

2019-06-27 06:46 UTC, HofmeisterAn commented on README.md
> +## Commands
I don't think all of these commands are supported yet by the official version. This is the list of my implementation.

2019-06-27 06:46 UTC, HofmeisterAn commented on README.md
> +Native Windows Docker containers are only supported on Windows. Windows requires the host operating system version to match the container operating system version. You'll find further information abo
We don't have any native Windows container yet.

2019-06-27 19:29 UTC, lalitkale commented on README.md
> +## Commands
yes, I reffered your implementation and readme for these commands. I was under assumption that after merging all three versions, we will be providing the same soon. Never mind, will revisit them with current implementation.

2019-06-27 19:30 UTC, lalitkale commented on README.md
> +Native Windows Docker containers are only supported on Windows. Windows requires the host operating system version to match the container operating system version. You'll find further information abo
okay, will remove it.

2019-06-28 04:04 UTC, HofmeisterAn commented on README.md
> +## Commands
I'm not sure if they match the official names. I would wait until we have taken over the functions, we will probably take more from @isen-ng, idk.

2019-12-27 03:26 UTC, jzabroski commented
This is a really useful README.md. what is left to merge it??

2019-12-27 07:05 UTC, isen-ng commented
@jzabroski We have left comments for the author but it seems that he hasn't implemented the changes.

Please reopen if there is any intention to get this PR back to latest and comments implemented.

2019-12-27 07:05 UTC, closed without merging

2019-12-27 10:58 UTC, jzabroski commented
That's lame. Why not accept it and fix it yourself? There's so much useful information here. Nobody will want to get involved with this project with its current README.md

2019-12-27 11:50 UTC, jzabroski commented
I guess the other odd thing is your personal master branch has these helpful docs but official project github doesn't. :(

2019-12-27 14:32 UTC, isen-ng commented
> That's lame. Why not accept it and fix it yourself? There's so much useful information here. Nobody will want to get involved with this project with its current README.md

Unfortunately, this is how it is. We do not want to copy his work and commit it using our own account, nor do want want to commit an incomplete PR, which will remain on his commit history forever like a stain.

> I guess the other odd thing is your personal master branch has these helpful docs but official project github doesn't. :(

My personal repository is something different from this. I hold full ownership of that repository and that is why I could advance it further without repercussions. On this organizational repository, maintainers must work as a team to discuss and agree on a PR/proposal before being committed. Sometimes, unfortunately, this takes a much longer time due to disagreements and conflicting schedules.

2019-12-27 15:14 UTC, jzabroski commented
Is your version hosted on Nuget.org?  It seems like your version and TestEnvironment.Docker are the state of the art; I'm leaning towards trying TestEnvironment.Docker first, as it has fluent async/await syntax which seems more flexible for testing scenarios like bringing up 10,000 nodes concurrently and having some of them die.