added sonarcube badges and appveyor branch status badges
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #61
Opened 2019-07-10 16:45 UTC by swissarmykirpan

There are a raft of badges we can add. Let me know what you think.

2019-07-11 01:29 UTC, isen-ng commented
This is a LOT of badges!

2019-07-11 01:29 UTC, isen-ng approved these changes

2019-07-11 06:16 UTC, HofmeisterAn requested changes

2019-07-11 06:16 UTC, HofmeisterAn commented on README.md
>  Nuget package can be found [here](https://www.nuget.org/packages/TestContainers/).
Shouldn't we use a badge for our NuGet package as well?

2019-07-11 06:16 UTC, HofmeisterAn commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=testcontainers_testcontainers-dotnet&metric=alert_status)](https://sonarcloud.io/dashboard?id=testcontainers_testconta
I think the Quality Gate (which we can define in SonarCloud) and the Coverage is enough. If someone is interested in more details he or she can use the link to SonarCloud.

2019-07-11 07:00 UTC, swissarmykirpan commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=testcontainers_testcontainers-dotnet&metric=alert_status)](https://sonarcloud.io/dashboard?id=testcontainers_testconta
Yeah I put them all up so we could see what they are. @isen-ng any opinion on this?

2019-07-11 09:40 UTC, swissarmykirpan commented on README.md
>  Nuget package can be found [here](https://www.nuget.org/packages/TestContainers/).
Do we want to replace the `Nuget package can be found here` text with a Nuget Badge (which when clicked takes you to the nuget url) ?

2019-07-11 09:42 UTC, swissarmykirpan commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=testcontainers_testcontainers-dotnet&metric=alert_status)](https://sonarcloud.io/dashboard?id=testcontainers_testconta
> I think the Quality Gate (which we can define in SonarCloud) and the Coverage is enough. If someone is interested in more details he or she can use the link to SonarCloud.

Having thought about this a little more, I don't see any harm having the extra badges. First impressions count and so having all the metrics available to begin with means the potential user doesn't have to click any further to find out important information about the code base, in which case all of the badges are important.

@isen-ng thoughts?

2019-07-12 01:54 UTC, isen-ng commented on README.md
>  Nuget package can be found [here](https://www.nuget.org/packages/TestContainers/).
How about something like this:
https://github.com/isen-ng/testcontainers-dotnet/blob/master/README.md#built-in-containers

2019-07-12 01:58 UTC, isen-ng commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=testcontainers_testcontainers-dotnet&metric=alert_status)](https://sonarcloud.io/dashboard?id=testcontainers_testconta
Personally, I prefer not to have too many dev-related badges.

The reason is that the more dev-related badges we show, the more we give people the impression that these MUST be fulfilled before the can successfully merge a PR. IMO, it may scare potential contributors away. We should only show the dev-badges that we are ver concerned with when accessing a PR.

However, usage-related badges? The more the merrier, to (attempt to) show our popularity.

2019-07-12 02:02 UTC, isen-ng commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=testcontainers_testcontainers-dotnet&metric=alert_status)](https://sonarcloud.io/dashboard?id=testcontainers_testconta
dev-related badges I would put:
Build status, static analysis and code coverage.

usage-related badges:
nuget package link, download count, github sponsor, etc, etc, etc

2019-07-16 14:14 UTC, isen-ng commented
I've made the changes.

You can see the preview here:
https://github.com/isen-ng/testcontainers-dotnet-1/tree/feature/add-badges

2019-07-17 05:49 UTC, HofmeisterAn commented
> I've made the changes.
> 
> You can see the preview here:
> https://github.com/isen-ng/testcontainers-dotnet-1/tree/feature/add-badges

LGTM! I like that.

2019-07-17 06:11 UTC, isen-ng commented
I have no clue how to setup github sponsors yet but I guess I can figure that out later.

2019-07-17 07:59 UTC, HofmeisterAn commented
> I have no clue how to setup github sponsors yet but I guess I can figure that out later.

I think it's still in beta and not available for everyone.

2019-07-17 08:00 UTC, HofmeisterAn approved these changes

2019-07-17 08:56 UTC, merged