#64 Fix SonarCloud code smells and refactore inconsitent code
docker-archive-public/testcontainers.testcontainers-dotnet-legacy pull request #65
Opened 2019-07-25 18:14 UTC by HofmeisterAn

2019-07-26 05:22 UTC, isen-ng commented
I think we should put the breaking changes in the next milestone

2019-07-26 05:35 UTC, isen-ng requested changes

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/Container.cs
> +                Stream logs = null;
Why is such a round-about way of disposing the `logs` var needed?
I don't understand why the original `using` statement is not sufficient.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/MySqlContainer.cs
> +        public const string TAG = "5.7";
DotNet naming convention says that constant variable names should be in PascalCase. I personally don't like it too, but since this is an open-source project that everyone else who adheres to standards will see and use, I prefer to stick to official conventions.

See this and search for `const` on the page
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/MySqlContainer.cs
> +        public const int PORT = 3306;
Let's not make this breaking change in this iteration

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/MySqlContainer.cs
> +        private const string DEFAULT_DATABASE_NAME = "test";
PascalCase and it seems like MySQL container does not create a database if this variable is not supplied.
I think we should supply a default (and document it) so that it's less painful for the user who will be using this for the first time.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/MySqlContainer.cs
> +        private const string DEFAULT_USERNAME = "root";
PascalCase and I don't think this can be `root`.

MySQL auto creates the root superuser and the extra user variable will create a new user for the db created above.

So, let's name it something like `test-user`

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/MySqlContainer.cs
> +        private const string DEFAULT_PASSWORD = "Password123";
PascalCase. There is no default in MySQL container and it's mandatory to set the root password. So i think setting something here (and indicating in the documentation) is fine.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/PostgreSqlContainer.cs
> +        private const string DEFAULT_PASSWORD = "Password123";
PascalCase and default postgres password is an empty string.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/PostgreSqlContainer.cs
> +        private const string DEFAULT_DATABASE_NAME = "test";
PascalCase and default postgres username is postgres

I prefer not to stray from the original defaults of postgres and it's official images because starting the container without any config, should just "work", eg use the original default values, so that the user will not need to scour the code to figure out what we did that is causing the confusion.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/PostgreSqlContainer.cs
> +        public const string TAG = "9.6.8";
Let's not make breaking changes yet.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/PostgreSqlContainer.cs
> +        public const int PORT = 5432;
Let's not make breaking changes yet.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/RabbitMQContainer.cs
> +        public const string IMAGE = "rabbitmq";
Let's not make breaking changes yet.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/RabbitMQContainer.cs
> +        public const string TAG = "3.7-alpine";
Let's not make breaking changes yet.

2019-07-26 05:35 UTC, isen-ng commented on src/TestContainers/Core/Containers/RabbitMQContainer.cs
> +        public const int PORT = 5672;
Let's not make breaking changes yet.

2019-07-26 05:55 UTC, HofmeisterAn commented
> I think we should put the breaking changes in the next milestone @HofmeisterAn

Okay, I'm gonna undo. I wanted to use Pascal Case first, but it was inconsistent again.

2019-07-26 05:57 UTC, HofmeisterAn commented on src/TestContainers/Core/Containers/Container.cs
> +                Stream logs = null;
I didn't know about the rule either: https://rules.sonarsource.com/csharp/RSPEC-3966?search=stream

2019-07-26 06:50 UTC, isen-ng commented
Hmm being inconsistent or using non-standard naming convention? decisions decisions....

Personally, I think for private constants, we can safely switch to PascalCase, and for the existing public constants, will remain ALL_CAPS.

Hopefully, we are not introducing anymore public constants at this point. This way, we are consistent that all internal facing are standard naming compliant, and public constants remain unchanged (because this release non-breaking).

What do you guys think? @HofmeisterAn @swissarmykirpan

2019-07-27 21:10 UTC, swissarmykirpan commented on src/TestContainers/Core/Containers/Container.cs
> +            await _dockerClient.Containers.ExecCreateContainerAsync(_containerId, containerExecCreateParams);
this line is actually not correct - has been fixed in `master`. I will merge the two and create a new develop most likely early next week.

2019-07-27 21:13 UTC, swissarmykirpan requested changes
need to wait until develop and master have been merged - and a new develop is created

2019-07-29 06:14 UTC, HofmeisterAn commented on src/TestContainers/Core/Containers/Container.cs
> +            await _dockerClient.Containers.ExecCreateContainerAsync(_containerId, containerExecCreateParams);
Ok, I have prepared the suggestions of @isen-ng. As soon as the fix is on `develop`, I'll rebase and update the PR.

2019-09-18 15:32 UTC, closed without merging